name: publish-docs

on:
  push:
    branches: [ master ]

jobs:
  pubdocs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout nmr_sims
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: setup python3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install nmrespy dependencies and sphinx and build docs
        run: |
          python -m pip install --upgrade pip
          cd master/
          python -m pip install -r requirements.txt
          cd docs/
          python -m pip install -r requirements.txt
          sphinx-build -b html . html

      - name: checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: update gh-pages
        run: |
          cd gh-pages
          cp -r ../master/docs/html/* .
          touch .nojekyll
          git config --local user.name "GitHub Actions"
          git config --local user.email "<>"
          git add -A
          git commit -m "Update documentation" || true
          git push
